/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_billthefarmer_accordion_MidiDriver */

#ifndef _Included_org_billthefarmer_accordion_MidiDriver
#define _Included_org_billthefarmer_accordion_MidiDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_billthefarmer_accordion_MidiDriver
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_accordion_MidiDriver_init
  (JNIEnv *, jobject);

/*
 * Class:     org_billthefarmer_accordion_MidiDriver
 * Method:    write
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_accordion_MidiDriver_write
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_billthefarmer_accordion_MidiDriver
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_billthefarmer_accordion_MidiDriver_shutdown
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
